name: BuyCraft
main: buycraft\BuyCraft
version: 0.3
author: Falk
api: [1.0.0]
load: POSTWORLD
permissions:
 buycraft:
  default: op
  description: Top level BuyCraft permission
  children:
   buycraft.admin:
    default: op
   buycraft.buy:
    default: true